name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm i
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy to http://health-advisers-portal.c1.biz
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: f14-preview.biz.nf
          port: 21
          username: 2078096
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: ./home/www/health-advisers-portal.c1.biz/
          dangerous-clean-slate: true