name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm i
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy to http://health-advisers-portal.c1.biz
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: files.000webhost.com
          ftp_username: wfefwefwef
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "build"
          dist_target_dir: "public_html"
          delete: "true"

      